name: flutter_app
description: BLoc example

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  equatable : ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
